add English version of PostPagination
Magicianred/learn-by-doing pull request #16
Opened 2021-01-07 18:40 UTC by marzieh1980

I add dataBase , Domain Project , UnitTest DAL and DAL project. Please check if its ok. 
Thank you.

2021-01-09 10:14 UTC, Magicianred commented on MyBlogSample/Features/PostPagination.md
> +- Add a test to *PostsRepositoryTest.cs* class in the */Repositories* folder, add a tset method named *should_retrieve_all_paginated_posts*. use the method *should_retrieve_all_posts* as a trace, cop
I think *retrieve* is better than *recovery* in this case, but I am not sure

2021-01-09 10:15 UTC, Magicianred commented on MyBlogSample/Features/PostPagination.md
> +##### Progetto DAL
*Progetto* is remain in italian :)

2021-01-09 10:18 UTC, Magicianred commented on MyBlogSample/Features/PostPagination.md
> +Tomas suggests adding pagination to the *Index* action of the *HomeController* controller to allow to be displayed only 3 posts at a time. Two parameters will be passed in the querystring, one for th
I usually use *Tom*, because I think is more informal

2021-01-09 10:18 UTC, marzieh1980 commented on MyBlogSample/Features/PostPagination.md
> +- Add a test to *PostsRepositoryTest.cs* class in the */Repositories* folder, add a tset method named *should_retrieve_all_paginated_posts*. use the method *should_retrieve_all_posts* as a trace, cop
You'r right. I will correct it. Thanks.

2021-01-09 10:20 UTC, marzieh1980 commented on MyBlogSample/Features/PostPagination.md
> +##### Progetto DAL
thank you. i will try to control more before sending PR.

2021-01-09 10:20 UTC, Magicianred requested changes
Well done. I just indicate few comment that I think can be changed.
I wait the rest of the text for merge it.

Thanks again Marzieh :)

2021-01-09 10:21 UTC, marzieh1980 commented on MyBlogSample/Features/PostPagination.md
> +Tomas suggests adding pagination to the *Index* action of the *HomeController* controller to allow to be displayed only 3 posts at a time. Two parameters will be passed in the querystring, one for th
I missed that one. thanks

2021-01-09 10:47 UTC, marzieh1980 commented
> Well done. I just indicate few comment that I think can be changed.
> I wait the rest of the text for merge it.
> 
> Thanks again Marzieh :)

I will do that. Thank you.

2021-01-10 09:18 UTC, Magicianred approved these changes
Great job! Thanks 👍 

I will also proceed to correct the name of the test method that you reported to me. :)

2021-01-10 09:19 UTC, merged