Marzieh1980 patch 1
Magicianred/learn-by-doing pull request #4
Opened 2020-11-28 12:45 UTC by marzieh1980

Hi. I add the English version of "Add Author to Posts" project.
I have doubts about some word's translation. please verify, Thanks.

2020-11-28 13:54 UTC, Magicianred commented on MyBlogSample/Features/PostAuthor.md
> +Jim would like to involve other friends to write posts of blog, so he needs to indicate in the posts who is the author. At the moment he think it not is necessary to create the Authors entity, it wil
indicate the author as a string.

2020-11-28 13:56 UTC, Magicianred commented on MyBlogSample/Features/PostAuthor.md
> +- Add the property *Author* in the *Ipost.cs* interface in */Interfaces/Models/Ipost.cs*, and consequently for the */Models/Post.cs* class.
the class is *Post*, the interface add a capital I, so *IPost.cs*

2020-11-28 14:04 UTC, Magicianred commented on MyBlogSample/Features/PostAuthor.md
> +- Modify the method *GetDefaultMockData* in the *PostsHelper* class in */Helpers* folder adding the enhancement of the new Author property.
With "aggiungendo la valorizzazione della nuova proprietà" I would like say "enter a value into the property"

2020-11-28 14:04 UTC, Magicianred commented on MyBlogSample/Features/PostAuthor.md
> +- Modify the *should_retrieve_all_posts e should_retrieve_post_by_id* test by adding an *Assert* which verifies the correct enhancement of the Author property.
"enhancement" is not correct

2020-11-28 14:06 UTC, Magicianred commented on MyBlogSample/Features/PostAuthor.md
> +- Modify the *GetDefaultMockData* method of PostsHelper class in the */Helpers* folder adding the enhancement of the new Author property.
"enhancement" is not correct

2020-11-28 14:08 UTC, Magicianred commented on MyBlogSample/Features/PostAuthor.md
> +- Modify the *Index* action in *HomeController* in the way which recieve an author parameter of string-type.
"recieve" there is a typo

2020-11-28 14:08 UTC, Magicianred commented on MyBlogSample/Features/PostAuthor.md
> +and if enhanced, call the new GetAllByAuthor method of the service instead of GetAll:
"enhanced" is not correct

2020-11-28 14:11 UTC, Magicianred requested changes
Thanks again Marzieh for your contribute :)
I have added some comment where I think need some review in order to merge

Anyway well done :) Thanks

2020-11-28 23:05 UTC, marzieh1980 commented
Thank you for the opportunity :)


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

On Sat, Nov 28, 2020 at 3:11 PM Simone Paolucci <notifications@github.com>
wrote:

> *@Magicianred* requested changes on this pull request.
>
> Thanks again Marzieh for your contribute :)
> I have added some comment where I think need some review in order to merge
>
> Anyway well done :) Thanks
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Magicianred/learn-by-doing/pull/4#pullrequestreview-540377898>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANV4QVSD4LZJ22ODBOWL2I3SSEAJZANCNFSM4UFYYGCA>
> .
>

2020-11-28 23:07 UTC, marzieh1980 commented on MyBlogSample/Features/PostAuthor.md
> +- Add the property *Author* in the *Ipost.cs* interface in */Interfaces/Models/Ipost.cs*, and consequently for the */Models/Post.cs* class.
Thanks. i have to control more, sorry.

2020-11-28 23:10 UTC, marzieh1980 commented on MyBlogSample/Features/PostAuthor.md
> +- Modify the method *GetDefaultMockData* in the *PostsHelper* class in */Helpers* folder adding the enhancement of the new Author property.
ok, i had doubt about this. never have to trust google translate ;)

2020-11-29 14:54 UTC, marzieh1980 reviewed
changes applied. I mentioned some comment in details. Thanks again.

2020-11-29 14:54 UTC, marzieh1980 commented on MyBlogSample/Features/PostAuthor.md
> +- Modify the *Index* action in *HomeController* in the way which recieve an author parameter of string-type.
what means recieve is typo? 
" riceva un parametro author di tipo stringa" this means: 
  recieve a parameter type of string (parameter is author) . not correct?

2020-11-29 14:54 UTC, marzieh1980 commented on MyBlogSample/Features/PostAuthor.md
> +Jim would like to involve other friends to write posts of blog, so he needs to indicate in the posts who is the author. At the moment he think it not is necessary to create the Authors entity, it wil
maybe we it will be modify also in Italian version! ?

2020-11-29 14:57 UTC, marzieh1980 commented
changes applied. Thanks

2020-11-29 14:57 UTC, marzieh1980 commented
Changes applied. Thanks.

2020-12-06 10:48 UTC, Magicianred approved these changes

2020-12-06 10:48 UTC, merged